### ISSUE TITLE
重启ob后，自定义视图元素消失

### ISSUE THREAD

**Issue by ssjy1919** [guopenghui/obsidian-vue-starter#1]
你好，重启ob后，自定义视图还在，但里面的HTML元素消失，了只有一个空白的标签页。我应该怎么做？

**Comment by WHG555** [comment]
我也遇到了这个问题，怎么解决了

**Comment by guopenghui** [comment]
在命令里面找 quiet outline 尝试打开。

一般重启不会导致视图消失，现在还不太清楚原因

**Comment by WHG555** [comment]
> 在命令里面找 quiet outline 尝试打开。
> 
> 一般重启不会导致视图消失，现在还不太清楚原因

现在是一定会发生。只要直接关闭ob。再打开。界面就成空白了

**Comment by guopenghui** [comment]
> > 在命令里面找 quiet outline 尝试打开。
> > 
> > 一般重启不会导致视图消失，现在还不太清楚原因
> 
> 现在是一定会发生。只要直接关闭ob。再打开。界面就成空白了

这个之前也有人提，但是没能复现。我每天都打开ob，大纲一直都保持上次退出时的状态。

**Comment by WHG555** [comment]
我这里每次都会出现这个问题，要不我加您个好友。看一下什么情况

**Comment by WHG555** [comment]
我的qq是  1002285542

**Comment by WHG555** [comment]
您好，我可以帮您一起定位一下这个问题么

**Comment by guopenghui** [comment]
我看错问题了，还以为是quiet outline下面的issue。。。那里之前有时有这个问题但是很难复现

 刚刚试了一下，在view.onOpen这里，用 `container.createEl()`创建元素后，好像元素不会被马上插入dom树，导致 `app.mount`的时候用选择器找不到元素。但是如果直接引用元素，就没问题。

```js
// 创建元素
container.createEl("div", {
    cls: "my-plugin-view"
});
let ee = document.querySelector(".my-plugin-view") 
console.log(ee) // null

app.mount(".my-plugin-view") // 找不到该元素
```

解决办法就是直接引用创建的元素：
```js
let elem = container.createEl("div", {
    cls: "my-plugin-view"
});

this.vueapp = createApp(App);
this.vueapp.mount(elem);  // 这里改一下
```

或者直接挂载在container上应该也行，但是最好还是加一层，后面方便通过document.querySelector来找view内的元素。

**Comment by WHG555** [comment]
谢谢大佬，问题解决了
