### ISSUE TITLE
请问 vue文件中，要怎么获取plugin的实例了。

### ISSUE THREAD

**Issue by WHG555** [guopenghui/obsidian-vue-starter#2]
我想在vue文件中，创建文件，打开文件。
想要调用我创建的插件的实例，但是不知道要怎么写。

**Comment by guopenghui** [comment]
我一般用三种方法：
1. 把plugin作为全局变量传到vue实例里面：
https://github.com/guopenghui/obsidian-language-learner/blob/0b6839b7cb9df6ca332e6495dd68065a3dc0e267/src/views/SearchPanelView.ts#L34-L36
然后在vue实例里面使用：
https://github.com/guopenghui/obsidian-language-learner/blob/0b6839b7cb9df6ca332e6495dd68065a3dc0e267/src/views/SearchPanel.vue#L35

2. 创建一个单独的ts文件，导出一个store对象。把store导入到plugin所在文件，在plugin初始化的时候把this存入store的属性里面。然后在vue里面import该store对象，从而访问plugin（按`store.plugin`的形式）。注意不要把store设置成reactive，否则会弄出很多没用的响应式对象。

3. 通过自定义事件来传递消息。vue里面发送，plugin里面接收（下面这个例子是反过来的，vue里面注册事件，plugin里面发送事件，来实现plugin和vue的通信）：
https://github.com/guopenghui/obsidian-language-learner/blob/0b6839b7cb9df6ca332e6495dd68065a3dc0e267/src/views/SearchPanel.vue#L137-L143
https://github.com/guopenghui/obsidian-language-learner/blob/0b6839b7cb9df6ca332e6495dd68065a3dc0e267/src/plugin.ts#L469-L471
这种方法写起来麻烦一些，但是比较灵活，可以实现plugin与vue通信、vue与plugin通信、vue组件之间的通信


上面的第2种方法，我一般不用来保存plugin，而是用来让设置选项立刻发挥作用。比如说你有一个设置选项fontColor值是红色，在vue组件创建的时候引用plugin.settings.fontColor把字体设置为红色，但是当设置选项改成蓝色的时候，vue组件并不会变化，因为这个fontColor不是响应式的。我会把store设置为reactive，然后在里面设置一个相同字段store.fontColor，vue组件通过这个store.fontColor来设置值。然后在修改设置选项的时候同时修改这个store.fontColor，这样修改就会立刻作用到vue组件上。可以看看这里fontSize的用法：

https://github.com/guopenghui/obsidian-language-learner/blob/0b6839b7cb9df6ca332e6495dd68065a3dc0e267/src/store.ts#L7C18-L7C18

**Comment by guopenghui** [comment]
https://github.com/guopenghui/obsidian-language-learner/blob/0b6839b7cb9df6ca332e6495dd68065a3dc0e267/src/views/SearchPanelView.ts#L34-L36

**Comment by WHG555** [comment]
谢谢大佬，我已经修改好了。   我使用您的模板做了这个插件 [https://github.com/WHG555/lunar-calendar](https://github.com/WHG555/lunar-calendar)  欢迎您指点。

**Comment by guopenghui** [comment]
嗯
